#!/usr/bin/env php
<?php

// define base directory
define('MC_PATH', realpath(dirname(__FILE__)));

// include mclistener
require_once(MC_PATH . "/mcl_files/lib/mclistener.php");

// run
$listener = new MCListener($argv);
